janephp/janephp

composer.json, src/OpenApi/JaneOpenApi.php, src/OpenApi/composer.json
Create this PR after discussing about https://github.com/janephp/openapi/pull/70.
Replace `fitbug/symfony-yaml-serializer-encoder-decoder` seems because to be not maintened anymore and the Symfony Serializer component implements its own YAML encoder/decoder.
=>  Remove fitbug/symfony-yaml-serializer-encoder-decoder in place of default YAML serializer

src/OpenApiRuntime/Client/Psr7HttplugClient.php
If the endpoint looks like this 'customer?action=list' and a query
string is passed to executePsr7Endpoint() the resulting
uri is broken.
Endpoint: /customer?action=list
QueryParam: sort=creation_date
Expected result:
/customer?action=list&sort=creation_date
Actual result:
/customer?action=list?sort=creation_date
---------------------^------------------
=> Fix issue with endpoint url containing an '?'

.travis.yml, composer.json
This PR
💁‍♂️ For reference, see https://github.com/localheinz/composer-normalize.
=> Enhancement: Normalize composer.json

src/OpenApi/Generator/ExceptionGenerator.php
After https://github.com/janephp/janephp/pull/61, there is a missing `parserException()` in `ExceptionGenerator`, thanks to @michaelthieulin to spot this one
=> Quick fix for OpenApi/ExceptionGenerator

src/OpenApi/Generator/ExceptionGenerator.php, src/OpenApi/Tests/fixtures/exception-with-no-schema/.jane-openapi, src/OpenApi/Tests/fixtures/exception-with-no-schema/expected/One/Client.php, src/OpenApi/Tests/fixtures/exception-with-no-schema/expected/One/Endpoint/TestOne.php, src/OpenApi/Tests/fixtures/exception-with-no-schema/expected/One/Exception/ApiException.php, src/OpenApi/Tests/fixtures/exception-with-no-schema/expected/One/Exception/ClientException.php, src/OpenApi/Tests/fixtures/exception-with-no-schema/expected/One/Exception/ServerException.php, src/OpenApi/Tests/fixtures/exception-with-no-schema/expected/One/Exception/TestOneNotFoundException.php, src/OpenApi/Tests/fixtures/exception-with-no-schema/expected/One/Model/TestOneGetResponse200.php, src/OpenApi/Tests/fixtures/exception-with-no-schema/expected/One/Normalizer/NormalizerFactory.php, src/OpenApi/Tests/fixtures/exception-with-no-schema/expected/One/Normalizer/TestOneGetResponse200Normalizer.php, src/OpenApi/Tests/fixtures/exception-with-no-schema/expected/Two/Client.php, src/OpenApi/Tests/fixtures/exception-with-no-schema/expected/Two/Endpoint/TestTwo.php, src/OpenApi/Tests/fixtures/exception-with-no-schema/expected/Two/Exception/ApiException.php, src/OpenApi/Tests/fixtures/exception-with-no-schema/expected/Two/Exception/ClientException.php, src/OpenApi/Tests/fixtures/exception-with-no-schema/expected/Two/Exception/ServerException.php, src/OpenApi/Tests/fixtures/exception-with-no-schema/expected/Two/Exception/TestTwoNotFoundException.php, src/OpenApi/Tests/fixtures/exception-with-no-schema/expected/Two/Model/TestTwoGetResponse200.php, src/OpenApi/Tests/fixtures/exception-with-no-schema/expected/Two/Normalizer/NormalizerFactory.php, src/OpenApi/Tests/fixtures/exception-with-no-schema/expected/Two/Normalizer/TestTwoGetResponse200Normalizer.php, src/OpenApi/Tests/fixtures/exception-with-no-schema/swagger_one.yaml, src/OpenApi/Tests/fixtures/exception-with-no-schema/swagger_two.yaml
When using `mapping` configuration with several schemas and atleast two of them having exceptions (status codes different than 200). Jane will generate base exception interfaces only for the first schema and ignore after that one.
This PR bring a fix to that and related test.
=> Fixing missing exception interfaces

src/OpenApi/Generator/EndpointGenerator.php, src/OpenApi/Generator/ExceptionGenerator.php
Fix missing public statements for generated endpoints & exceptions.
This was already fixed on `4.x` branch (with #61 PR), so let's fix it in `master` aswell :wink:
=> Fix missing public statements

src/OpenApi/helpers.php
When added `nikic/php-parser` 4.x compatibility, I forgot to also add the `helper.php` file in OpenApi folder ~
cf. https://github.com/janephp/janephp/pull/61
=> Missing helper file for OpenApi library

src/OpenApiRuntime/Client/Psr7HttplugEndpointTrait.php, src/OpenApiRuntime/Tests/Client/Psr7HttplugClientTest.php, src/OpenApiRuntime/Tests/Client/Psr7HttplugEndpointTraitTest.php
try to fetch the Content-Type from the body before passing it to the transform function.
fixes #75
=> get the content type from the header and pass it to the transformResponseBody function

src/OpenApiRuntime/Client/Psr7HttplugEndpointTrait.php, src/OpenApiRuntime/Tests/Client/Psr7HttplugClientTest.php, src/OpenApiRuntime/Tests/Client/Psr7HttplugEndpointTraitTest.php
fix for #76 for the `4.x` branch
=> v4: get the content type from the header and pass it to the transformResponseBody function

CHANGELOG.md, src/OpenApi/Generator/EndpointGenerator.php, src/OpenApi/Tests/fixtures/parameters/expected/Endpoint/GetByTestInteger.php, src/OpenApi/Tests/fixtures/uppercase-parameter/.jane-openapi, src/OpenApi/Tests/fixtures/uppercase-parameter/expected/Client.php, src/OpenApi/Tests/fixtures/uppercase-parameter/expected/Endpoint/TestGetWithUppercasePathParameters.php, src/OpenApi/Tests/fixtures/uppercase-parameter/expected/Normalizer/NormalizerFactory.php, src/OpenApi/Tests/fixtures/uppercase-parameter/swagger.json
This fix address issue #79 by removing `Inflector::camelize()` in EndpointGenerator class for property name in the constructor
=> Fix generated endpoint in case of uppercase in path parameter

src/OpenApi/Generator/EndpointGenerator.php, src/OpenApi/Tests/fixtures/parameters/expected/Endpoint/GetByTestInteger.php, src/OpenApi/Tests/fixtures/uppercase-parameter/.jane-openapi, src/OpenApi/Tests/fixtures/uppercase-parameter/expected/Client.php, src/OpenApi/Tests/fixtures/uppercase-parameter/expected/Endpoint/TestGetWithUppercasePathParameters.php, src/OpenApi/Tests/fixtures/uppercase-parameter/expected/Normalizer/NormalizerFactory.php, src/OpenApi/Tests/fixtures/uppercase-parameter/swagger.json
Same as #97 but for master branch
=>  Fix generated endpoint in case of uppercase in path parameter

src/OpenApi/Generator/EndpointGenerator.php, src/OpenApi/Tests/fixtures/array-definition/expected/Endpoint/TestSimple.php, src/OpenApi/Tests/fixtures/exceptions/expected/Endpoint/TestNoTag.php, src/OpenApi/Tests/fixtures/from-url/expected/Endpoint/CreatePets.php, src/OpenApi/Tests/fixtures/from-url/expected/Endpoint/ListPets.php, src/OpenApi/Tests/fixtures/from-url/expected/Endpoint/ShowPetById.php, src/OpenApi/Tests/fixtures/model-in-response/expected/Endpoint/GetEmptyTest.php, src/OpenApi/Tests/fixtures/model-in-response/expected/Endpoint/GetTest.php, src/OpenApi/Tests/fixtures/model-in-response/expected/Endpoint/GetTestById.php, src/OpenApi/Tests/fixtures/model-in-response/expected/Endpoint/GetTestList.php, src/OpenApi/Tests/fixtures/multi-specs/expected/Api1/Endpoint/TestReferenceResponse.php, src/OpenApi/Tests/fixtures/multi-specs/expected/Api2/Endpoint/TestReferenceResponse.php, src/OpenApi/Tests/fixtures/no-reference-response/expected/Endpoint/Test.php, src/OpenApi/Tests/fixtures/operations/expected/Endpoint/GetAnotherThing.php, src/OpenApi/Tests/fixtures/operations/expected/Endpoint/GetAnotherThingById.php, src/OpenApi/Tests/fixtures/operations/expected/Endpoint/GetThings.php, src/OpenApi/Tests/fixtures/operations/expected/Endpoint/GetThingsById.php, src/OpenApi/Tests/fixtures/response-reference/expected/Endpoint/TestRefArray.php, src/OpenApi/Tests/fixtures/response-reference/expected/Endpoint/TestReferenceResponse.php
When having Content-Type such as `application/json; charset=utf-8` we should extract first part and compare only first part.
=> Fix Content-Type comparison in generated endpoints

src/OpenApi/Generator/Normalizer/DenormalizerGenerator.php, src/OpenApi/Tests/fixtures/discriminator-snake-case/.jane-openapi, src/OpenApi/Tests/fixtures/discriminator-snake-case/expected/Client.php, src/OpenApi/Tests/fixtures/discriminator-snake-case/expected/Model/CatInSnakeCase.php, src/OpenApi/Tests/fixtures/discriminator-snake-case/expected/Model/DogInSnakeCase.php, src/OpenApi/Tests/fixtures/discriminator-snake-case/expected/Model/Pet.php, src/OpenApi/Tests/fixtures/discriminator-snake-case/expected/Normalizer/CatInSnakeCaseNormalizer.php, src/OpenApi/Tests/fixtures/discriminator-snake-case/expected/Normalizer/DogInSnakeCaseNormalizer.php, src/OpenApi/Tests/fixtures/discriminator-snake-case/expected/Normalizer/NormalizerFactory.php, src/OpenApi/Tests/fixtures/discriminator-snake-case/expected/Normalizer/PetNormalizer.php, src/OpenApi/Tests/fixtures/discriminator-snake-case/swagger.json
Related to https://github.com/janephp/janephp/issues/113
When a discriminator written in snake_case has been generated, the classname remains in snake_case instead camelCase.
I would like to write the tests, do you have any recommendations ?
=> Correct discriminator classname snake_case into camelCase for denormalization

src/OpenApi/Generator/Psr18ClientGenerator.php
We are using [`parse_url`](https://www.php.net/manual/en/function.parse-url.php) function in `Psr18ClientGenerator` class. This function returns an array with "potential keys" (quoted from documentation). So we have to check if key exists before using it.
=> [Psr18ClientGenerator] Check if path exists before using it

src/OpenApi/Generator/EndpointGenerator.php, src/OpenApi/Tests/fixtures/model-type-reference/.jane-openapi, src/OpenApi/Tests/fixtures/model-type-reference/expected/Client.php, src/OpenApi/Tests/fixtures/model-type-reference/expected/Model/Model.php, src/OpenApi/Tests/fixtures/model-type-reference/expected/Normalizer/ModelNormalizer.php, src/OpenApi/Tests/fixtures/model-type-reference/expected/Normalizer/NormalizerFactory.php, src/OpenApi/Tests/fixtures/model-type-reference/schema.json, src/OpenApi/Tests/fixtures/parameter-type-reference/.jane-openapi, src/OpenApi/Tests/fixtures/parameter-type-reference/expected/Client.php, src/OpenApi/Tests/fixtures/parameter-type-reference/expected/Endpoint/Foo.php, src/OpenApi/Tests/fixtures/parameter-type-reference/expected/Normalizer/NormalizerFactory.php, src/OpenApi/Tests/fixtures/parameter-type-reference/schema.json, src/OpenApi/Tests/fixtures/response-type-reference/.jane-openapi, src/OpenApi/Tests/fixtures/response-type-reference/expected/Client.php, src/OpenApi/Tests/fixtures/response-type-reference/expected/Endpoint/Foo.php, src/OpenApi/Tests/fixtures/response-type-reference/expected/Model/FooGetResponse200.php, src/OpenApi/Tests/fixtures/response-type-reference/expected/Normalizer/FooGetResponse200Normalizer.php, src/OpenApi/Tests/fixtures/response-type-reference/expected/Normalizer/NormalizerFactory.php, src/OpenApi/Tests/fixtures/response-type-reference/schema.json
Fixes #108 
Will resolve reference inside the `schema` field of a parameter.
=> Fix reference in endpoint parameter schema

src/OpenApi/composer.json
We conflict for versions lower than 4.5 since it introduce PSR-18 Client Generation with some breaking changes.
=> Conflict with jane < 4.5 for OpenApi runtime

src/JsonSchema/Generator/Model/ConstructGenerator.php, src/JsonSchema/Generator/ModelGenerator.php, src/JsonSchema/Generator/Naming.php, src/JsonSchema/Generator/Normalizer/DenormalizerGenerator.php, src/JsonSchema/Generator/Normalizer/NormalizerGenerator.php, src/JsonSchema/Generator/NormalizerGenerator.php, src/JsonSchema/Generator/PropertyCheckTrait.php, src/JsonSchema/Generator/Proxy/ClassGenerator.php, src/JsonSchema/Generator/Proxy/ConstructGenerator.php, src/JsonSchema/Generator/Proxy/PropertiesGenerator.php, src/JsonSchema/Generator/ProxyGenerator.php, src/JsonSchema/Guesser/Guess/Property.php, src/JsonSchema/Guesser/JsonSchema/ObjectGuesser.php, src/JsonSchema/Jane.php, src/JsonSchema/Tests/fixtures/read-only/.jane, src/JsonSchema/Tests/fixtures/read-only/expected/Model/Test.php, src/JsonSchema/Tests/fixtures/read-only/expected/Normalizer/NormalizerFactory.php, src/JsonSchema/Tests/fixtures/read-only/expected/Normalizer/TestNormalizer.php, src/JsonSchema/Tests/fixtures/read-only/expected/Proxy/ProxyTest.php, src/JsonSchema/Tests/fixtures/read-only/schema.json, src/OpenApi/Generator/Normalizer/NormalizerGenerator.php, src/OpenApi/JaneOpenApi.php
Related to #133 
Adding Proxy to models that are readOnly.
From specs:
> Relevant only for Schema "properties" definitions. Declares the property as "read only". This means that it MAY be sent as part of a response but SHOULD NOT be sent as part of the request. If the property is marked as readOnly being true and is in the required list, the required will take effect on the response only. A property MUST NOT be marked as both readOnly and writeOnly being true. Default value is false.
=> Adding Proxy generation for readOnly

src/OpenApi/Generator/RequestBodyContent/AbstractBodyContentGenerator.php, src/OpenApi/Generator/RequestBodyGenerator.php, src/OpenApi/Tests/fixtures/any-of-mixed-request-body-parameter-type/.jane-openapi, src/OpenApi/Tests/fixtures/any-of-mixed-request-body-parameter-type/expected/Client.php, src/OpenApi/Tests/fixtures/any-of-mixed-request-body-parameter-type/expected/Endpoint/TestMixedRequestBody.php, src/OpenApi/Tests/fixtures/any-of-mixed-request-body-parameter-type/expected/Normalizer/NormalizerFactory.php, src/OpenApi/Tests/fixtures/any-of-mixed-request-body-parameter-type/openapi.json
see #157 
Resolved parameter types for response bodies of type `mixed` are used as type hints in endpoint constructor and related client operation method signatures.
This PR fixes this by using the default parameter type `null` for these cases.
=> do not type hint mixed parameter types for request bodies in endpoint constructor and clients operations method

src/OpenApi/composer.json
Because it won't work for multipart forms otherwise
=> Conflict with jane-php/open-api < 4.5.2

src/OpenApi/Generator/Parameter/NonBodyParameterGenerator.php, src/OpenApi/Tests/fixtures/test-nullable/expected/Client.php, src/OpenApi/Tests/fixtures/test-nullable/expected/Endpoint/TestNullableQueryParameters.php, src/OpenApi/Tests/fixtures/test-nullable/schema.json, src/OpenApiRuntime/Client/BaseEndpoint.php
I am building a REST API according to an Openapi specifications file (V3). 
I have generated SDK with Jane but this one seems to not considering ```nullable: true``` attribute in request query parameters.
**My example openapi specs file:**
```
[...]
paths:
/tickets:
get:
summary: Get tickets according to filters
operationId: getTickets
parameters:
- in: query
name: status
required: false
schema:
type: string
- in: query
name: assigneeId
required: false
schema:
type: integer
nullable: true
[...]
```
**Source code generated by Jane in Endpoint/GetTickets.php::getQueryOptionsResolver():**
```
protected function getQueryOptionsResolver() : \Symfony\Component\OptionsResolver\OptionsResolver
{
$optionsResolver = parent::getQueryOptionsResolver();
$optionsResolver->setDefined(array('status', …
```
=> Handling of nullable attribute on query parameters

src/OpenApi/Generator/Psr18ClientGenerator.php
This fixes notice when you run `generate`:
```
PHP Notice:  Undefined offset: 0 in /app/vendor/jane-php/open-api/Generator/Psr18ClientGenerator.php on line 112
PHP Stack trace:
PHP   1. {main}() /app/vendor/jane-php/open-api/bin/jane-openapi:0
PHP   2. Jane\OpenApi\Application->run($input = *uninitialized*, $output = *uninitialized*) /app/vendor/jane-php/open-api/bin/jane-openapi:22
PHP   3. Jane\OpenApi\Application->doRun($input = *uninitialized*, $output = *uninitialized*) /app/vendor/symfony/console/Application.php:149
PHP   4. Jane\OpenApi\Application->doRunCommand($command = *uninitialized*, $input = *uninitialized*, $output = *uninitialized*) /app/vendor/symfony/console/Application.php:273
PHP   5. Jane\OpenApi\Command\GenerateCommand->run($input = *uninitialized*, $output = …
```
=> fixed undefined offset error

src/JsonSchema/Generator/Normalizer/NormalizerGenerator.php, src/OpenApi/Tests/fixtures/test-nullable-array/.jane-openapi, src/OpenApi/Tests/fixtures/test-nullable-array/expected/Client.php, src/OpenApi/Tests/fixtures/test-nullable-array/expected/Endpoint/TestNullableArray.php, src/OpenApi/Tests/fixtures/test-nullable-array/expected/Model/Model.php, src/OpenApi/Tests/fixtures/test-nullable-array/expected/Normalizer/ModelNormalizer.php, src/OpenApi/Tests/fixtures/test-nullable-array/expected/Normalizer/NormalizerFactory.php, src/OpenApi/Tests/fixtures/test-nullable-array/schema.json
This PR fixes #201 by extending the condition checking if the property is of type `ArrayType`
=> Fix nullable array types

src/JsonSchema/Generator/Normalizer/NormalizerGenerator.php, src/JsonSchema/Tests/fixtures/read-only/.jane, src/JsonSchema/Tests/fixtures/read-only/expected/Model/Foo.php, src/JsonSchema/Tests/fixtures/read-only/expected/Normalizer/FooNormalizer.php, src/JsonSchema/Tests/fixtures/read-only/expected/Normalizer/NormalizerFactory.php, src/JsonSchema/Tests/fixtures/read-only/schema.json, src/OpenApi/Tests/fixtures/api-platform-demo/expected/Normalizer/ParchmentNormalizer.php, src/OpenApi/Tests/fixtures/read-only-properties/.jane-openapi, src/OpenApi/Tests/fixtures/read-only-properties/expected/Client.php, src/OpenApi/Tests/fixtures/read-only-properties/expected/Model/Model.php, src/OpenApi/Tests/fixtures/read-only-properties/expected/Normalizer/ModelNormalizer.php, src/OpenApi/Tests/fixtures/read-only-properties/expected/Normalizer/NormalizerFactory.php, src/OpenApi/Tests/fixtures/read-only-properties/schema.json
This PR provides a simplified solution (compared to the v6 proxy approach) to add support for `readOnly` properties by normalizing only properties for the request payload model which are not marked with `readOnly: true`.
provides a solution for #133
=> Readonly property support

src/OpenApi/Generator/EndpointGenerator.php, src/OpenApi/Guesser/OpenApiSchema/GuesserFactory.php, src/OpenApi/Guesser/OpenApiSchema/OpenApiGuesser.php, src/OpenApi/Tests/fixtures/referenced-request-bodies/.jane-openapi, src/OpenApi/Tests/fixtures/referenced-request-bodies/expected/Client.php, src/OpenApi/Tests/fixtures/referenced-request-bodies/expected/Endpoint/GetParentsByParentIdChildChildId.php, src/OpenApi/Tests/fixtures/referenced-request-bodies/expected/Endpoint/PatchParentsByParentIdChildChildId.php, src/OpenApi/Tests/fixtures/referenced-request-bodies/expected/Model/Child.php, src/OpenApi/Tests/fixtures/referenced-request-bodies/expected/Model/Parent.php, src/OpenApi/Tests/fixtures/referenced-request-bodies/expected/Model/ParentsParentIdChildChildIdPatchBody.php, src/OpenApi/Tests/fixtures/referenced-request-bodies/expected/Normalizer/ChildNormalizer.php, src/OpenApi/Tests/fixtures/referenced-request-bodies/expected/Normalizer/JaneObjectNormalizer.php, src/OpenApi/Tests/fixtures/referenced-request-bodies/expected/Normalizer/NormalizerFactory.php, src/OpenApi/Tests/fixtures/referenced-request-bodies/expected/Normalizer/ParentNormalizer.php, src/OpenApi/Tests/fixtures/referenced-request-bodies/expected/Normalizer/ParentsParentIdChildChildIdPatchBodyNormalizer.php, src/OpenApi/Tests/fixtures/referenced-request-bodies/openapi3.yaml
Fixes #225 
I stumbled open 
```
Uncaught TypeError: Argument 1 passed to Jane\OpenApi\Generator\RequestBodyGenerator::getSerializeStatements() must be an instance of Jane\OpenApi\JsonSchema\Model\RequestBody or null, instance of Jane\JsonSchemaRuntime\Reference
```
and
```
Call to undefined method Jane\JsonSchemaRuntime\Reference::getContent()
```
when using an openapi specification with references in the request body. This is not an optimal fix but this will at least end up in a generated client. Whether the client is working correctly is still something to find out. I cannot provide a minimal example yet as I have to reduce the problem.
For now I need some feedback on that error and hints on solving this over all in this library.
=> Error on references in requestbody

src/JsonSchemaRuntime/Reference.php
The Pointer is created again and again with the same file.
22mn => 1mn24
Followup of #168
=> giganourmous perf improvment on big swagger json file

src/OpenApiCommon/Generator/AuthenticationGenerator.php
When you have many authentication types defined in OpenApi v3 specs:
```
jwt:
type: http
scheme: bearer
bearerFormat: JWT
apiKey:
type: apiKey
in: header
name: X-API-KEY
```
there is a variable conflit in Authentication generator. The $namespace variable is overwrited in `foreach` and doesn't contain the original value (string type) for next loops.
=> Fix variable conflict in authentication generator

src/JsonSchema/composer.json
`symfony/serializer` dependency is used but was not explicitly required in `composer.json`.
I set it to `"4.2 || ^5.0` since the lower versions are not supported.
=> Fixed JsonSchema dependencies

src/OpenApiCommon/Command/GenerateCommand.php
When you have multiple OpenAPI versions in same Jane configuration mapping file, we need to have atleast one registry per OpenAPI version
=> Fix multiple OpenAPI version in Jane mapping

src/OpenApi/Naming/OperationUrlNaming.php, src/OpenApi/Tests/fixtures/no-operation-id-with-dot-path/.jane-openapi, src/OpenApi/Tests/fixtures/no-operation-id-with-dot-path/expected/Client.php, src/OpenApi/Tests/fixtures/no-operation-id-with-dot-path/expected/Endpoint/PostMessageM700.php, src/OpenApi/Tests/fixtures/no-operation-id-with-dot-path/expected/Endpoint/PostMessageM70047.php, src/OpenApi/Tests/fixtures/no-operation-id-with-dot-path/expected/Model/MessageM70047PostBody.php, src/OpenApi/Tests/fixtures/no-operation-id-with-dot-path/expected/Model/MessageM700PostBody.php, src/OpenApi/Tests/fixtures/no-operation-id-with-dot-path/expected/Normalizer/JaneObjectNormalizer.php, src/OpenApi/Tests/fixtures/no-operation-id-with-dot-path/expected/Normalizer/MessageM70047PostBodyNormalizer.php, src/OpenApi/Tests/fixtures/no-operation-id-with-dot-path/expected/Normalizer/MessageM700PostBodyNormalizer.php, src/OpenApi/Tests/fixtures/no-operation-id-with-dot-path/expected/Normalizer/NormalizerFactory.php, src/OpenApi/Tests/fixtures/no-operation-id-with-dot-path/swagger.yaml
Given the following schema:
```yaml
openapi: 3.0.0
paths:
/message/M700:
post:
requestBody:
content:
application/json:
schema:
type: object
properties:
bar:
type: string
required: true
responses:
default:
description: Default response
/message/M700.47:
post:
requestBody:
content:
application/json:
schema:
type: object
properties:
bar:
type: string
required: true
responses:
default:
description: Default response
info:
version: ''
title: ''
components:
schemas: {}
```
We need to have the `47` in generated `operationId`, before we were ignoring any word starting by `.`, now we restrict this to know possible extensions (`.php`, `.json`, `.asp`)
=> Fix when no operationId is given on path with a dot

composer.json, src/OpenApiCommon/Naming/OperationIdNaming.php, src/OpenApiCommon/composer.json
Fixes #248 
I also introduced `symfony/string` to fix it, way easier that way, will probably refactor all Naming stuff with it later ~
=> Fixing issue where class names could contains dots

src/OpenApiRuntime/Client/BaseEndpoint.php
When i call an API endpoint with query string contains a ```0``` value, Jane convert it to empty string. Jane must only convert ```null``` values to empty string.
Example:
Endpoint ```https://monapi.dev/get_items``` called with ```limit=20``` and ```offset=0```
Today, Jane convert ```offset``` query parameter to empty string:
```https://monapi.dev/get_items?limit=20&offset=```
Url expected : 
```https://monapi.dev/get_items?limit=20&offset=0```
=> Fix null parameter to empty string transformation to keep zero value

composer.json, src/OpenApiCommon/composer.json
Missing `symfony/console` on both root repository & `open-api-common`
=> Fix dependencies

composer.json, src/JsonSchema/Application.php, src/JsonSchema/Command/ConfigLoader.php, src/JsonSchema/Command/DumpConfigCommand.php, src/JsonSchema/Command/GenerateCommand.php, src/JsonSchema/composer.json, src/OpenApiCommon/Application.php, src/OpenApiCommon/Command/DumpConfigCommand.php, src/OpenApiCommon/Command/GenerateCommand.php, src/OpenApiCommon/composer.json
Fixes #285
Add a new `dump-config` command to both JsonSchema & OpenApiCommon applications. This command allow you to dump your configuration file to know exactly what's inside (even when you have some strange logic :wink:)
=> Add new dump-config command

documentation/index.rst, documentation/tips/nullable.rst, src/JsonSchema/Generator/Model/GetterSetterGenerator.php, src/JsonSchema/Generator/Model/PropertyGenerator.php, src/JsonSchema/Generator/ModelGenerator.php, src/JsonSchema/Guesser/Guess/MultipleType.php, src/JsonSchema/Guesser/JsonSchema/MultipleGuesser.php, src/OpenApi2/Guesser/OpenApiSchema/MultipleGuesser.php, src/OpenApi2/Guesser/OpenApiSchema/SchemaGuesser.php, src/OpenApi2/Guesser/OpenApiSchema/SimpleTypeGuesser.php, src/OpenApi2/Tests/fixtures/nullable-check/.jane-openapi, src/OpenApi2/Tests/fixtures/nullable-check/expected/Client.php, src/OpenApi2/Tests/fixtures/nullable-check/expected/Model/Foo.php, src/OpenApi2/Tests/fixtures/nullable-check/expected/Normalizer/FooNormalizer.php, src/OpenApi2/Tests/fixtures/nullable-check/expected/Normalizer/JaneObjectNormalizer.php, src/OpenApi2/Tests/fixtures/nullable-check/swagger.json, src/OpenApiCommon/JaneOpenApi.php
Fixes #297
OpenAPI v2 does not support `null` type. We should use custom field such as `x-nullable`. See https://stackoverflow.com/a/48114322 for more details.
=> Fix OpenAPI v2 null support

src/OpenApi3/Tests/fixtures/whitelisted-paths-reference-without-content/.jane-openapi, src/OpenApi3/Tests/fixtures/whitelisted-paths-reference-without-content/expected/Client.php, src/OpenApi3/Tests/fixtures/whitelisted-paths-reference-without-content/expected/Endpoint/GetFoo.php, src/OpenApi3/Tests/fixtures/whitelisted-paths-reference-without-content/expected/Exception/ApiException.php, src/OpenApi3/Tests/fixtures/whitelisted-paths-reference-without-content/expected/Exception/ClientException.php, src/OpenApi3/Tests/fixtures/whitelisted-paths-reference-without-content/expected/Exception/GetFooUnauthorizedException.php, src/OpenApi3/Tests/fixtures/whitelisted-paths-reference-without-content/expected/Exception/ServerException.php, src/OpenApi3/Tests/fixtures/whitelisted-paths-reference-without-content/expected/Model/Foo.php, src/OpenApi3/Tests/fixtures/whitelisted-paths-reference-without-content/expected/Normalizer/FooNormalizer.php, src/OpenApi3/Tests/fixtures/whitelisted-paths-reference-without-content/expected/Normalizer/JaneObjectNormalizer.php, src/OpenApi3/Tests/fixtures/whitelisted-paths-reference-without-content/openapi.yaml, src/OpenApi3/Tests/fixtures/whitelisted-paths-request-body-reference/.jane-openapi, src/OpenApi3/Tests/fixtures/whitelisted-paths-request-body-reference/expected/Client.php, src/OpenApi3/Tests/fixtures/whitelisted-paths-request-body-reference/expected/Endpoint/PostFoo.php, src/OpenApi3/Tests/fixtures/whitelisted-paths-request-body-reference/expected/Model/FooPayload.php, src/OpenApi3/Tests/fixtures/whitelisted-paths-request-body-reference/expected/Normalizer/FooPayloadNormalizer.php, src/OpenApi3/Tests/fixtures/whitelisted-paths-request-body-reference/expected/Normalizer/JaneObjectNormalizer.php, src/OpenApi3/Tests/fixtures/whitelisted-paths-request-body-reference/openapi.yaml, src/OpenApi3/WhitelistedSchema.php
**Bug fix:**
When you want to generate an endpoint who has a referenced response without content (simple 401/403 responses for example), the `Jane\OpenApi3\WhitelistedSchema` class throw an exception because `Jane\OpenApi3\JsonSchema\Model\Reference` object has no `getContent()` method. 
**Improvement:**
In POST endpoint, `requestBody` object/reference is not processing by `Jane\OpenApi3\WhitelistedSchema::addOperationRelations` method and referenced Model is not added to relations array.
=> Improvement & fix on whitelisted path feature

src/OpenApi3/Generator/Parameter/NonBodyParameterGenerator.php, src/OpenApi3/Tests/fixtures/parameters/expected/Client.php, src/OpenApi3/Tests/fixtures/parameters/expected/Endpoint/TestDictionary.php, src/OpenApi3/Tests/fixtures/parameters/swagger.json
Fixes #313 
Will allow dictionary types in parameters for OpenAPI 3 using:
```yaml
parameters:
- name: input
in: query
required: true
schema:
type: object
additionalProperties:
type: string
```
=> Allow dictionary parameters for OpenAPI 3

composer.json, src/AutoMapper/composer.json, src/JsonSchema/composer.json, src/JsonSchemaRuntime/composer.json, src/OpenApi2/composer.json, src/OpenApi3/composer.json, src/OpenApiCommon/composer.json, src/OpenApiRuntime/composer.json
Same as #327 but for `master` branch
> Fixes #323 
> 
> I didn't changed `symfony/string`, it's a new component since Symfony 5.x and it doesn't require any other Symfony component so it shouln'd be an issue.
> 
> I also restricted Symfony to `5.0.*` (instead of `^5.0`), because we have an issue with Serializer container definition in `5.1` (see for more details https://github.com/symfony/symfony/pull/37058)
=> Fix 6.x dependencies

src/AutoMapper/Tests/Transformer/StringToDateTimeTransformerTest.php, src/AutoMapper/Transformer/StringToDateTimeTransformer.php
When a `setter` is casted with a `DateTimeInterface`, the automapper try to create an instanceof `DateTimeInterface`.
When `DateTimeInterface` is given as class name, we fallback on a `DateTimeImmutable` instead.
=> Do not try to create an instance of an interface

documentation/components/AutoMapper.rst, src/AutoMapper/Bundle/DependencyInjection/Configuration.php, src/AutoMapper/Bundle/DependencyInjection/JaneAutoMapperExtension.php, src/AutoMapper/Bundle/Resources/config/services.xml, src/AutoMapper/MapperGeneratorMetadataFactory.php
When using the bundle it's currently not possible to use a custom date format.
=> Allow date_time_format override from bundle

src/OpenApi3/Generator/Parameter/NonBodyParameterGenerator.php, src/OpenApi3/Tests/fixtures/issue-299/.jane-openapi, src/OpenApi3/Tests/fixtures/issue-299/expected/Client.php, src/OpenApi3/Tests/fixtures/issue-299/expected/Endpoint/GetUsers.php, src/OpenApi3/Tests/fixtures/issue-299/expected/Normalizer/JaneObjectNormalizer.php, src/OpenApi3/Tests/fixtures/issue-299/swagger.yaml
=> Handle references in operation responses

composer.json
Avoid composer warnings for almost all tests classes:
```
Deprecation Notice: Class Jane\OpenApi3\Tests\Expected\Endpoint\GetAnotherThing located in ./vendor/jane-php/jane-php/src/OpenApi3/Tests/fixtures/operations/expected/Endpoint/GetAnotherThing.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
```
=> Exclude tests from classmap

src/AutoMapper/Tests/AutoMapperTest.php, src/AutoMapper/Tests/Fixtures/User.php, src/AutoMapper/Tests/Fixtures/UserDTOProperties.php, src/AutoMapper/Tests/Transformer/ArrayTransformerFactoryTest.php, src/AutoMapper/Transformer/ArrayTransformerFactory.php
When source & target are equals, directly use a `CopyTransformer` instead of a `ArrayTransformer` containing a `CopyTransformer` which don't preserve keys.
=> Use copy transformer for sibling arrays

src/JsonSchema/Guesser/JsonSchema/ArrayGuesser.php
When having a schema as following:
```json
{
"schema": {
"properties": {
"comments": {
"items": {},
"type": "array"
}
}
}
}
```
We had an empty array which was not matched as empty, this PR fix it and permit to be recognize as `mixed` type for this array.
=> Fixed array items with mixed types

composer.json, src/AutoMapper/composer.json, src/JsonSchema/composer.json
As `doctrine/orm` (& maybe a few others) doesn't support `doctrine/inflector` in its latest stable release yet, let's accept `doctrine/inflector` 1.x.
=> Supports both inflector v1 & v2
