src/JsonSchema/Guesser/JsonSchema/AllOfGuesser.php
src/JsonSchema/Guesser/JsonSchema/ObjectGuesser.php

Diving through the source  discovered a possible typo.

Typo oattern -> pattern

---

composer.json
src/JsonSchema/Registry.php
src/JsonSchemaRuntime/Reference.php
src/JsonSchemaRuntime/composer.json

Upgrade league/uri to 5.0

---

.travis.yml

This PR
💁‍♂️ For reference, see `composer.json`: 
https://github.com/janephp/janephp/blob/bd618aff1ac9cc001cf90642076220525c2f9c71/composer.json#L43.

Fix: Use php-cs-fixer as installed with composer

---

src/AutoMapper/composer.json
src/JsonSchema/composer.json
src/JsonSchemaRuntime/composer.json
src/OpenApi/composer.json
src/OpenApiRuntime/composer.json

Enhancement: Keep packages sorted in composer.json

---

src/JsonSchema/Generator/Normalizer/NormalizerGenerator.php

Fix: DocBlock

---

documentation/JsonSchema/usage.rst

Update JsonEncode / JsonDecode constructor for Symfony >= 4.2

---

src/OpenApi/Generator/EndpointGenerator.php
src/OpenApi/Tests/fixtures/yaml/expected/Endpoint/TestReferenceResponse.php
src/OpenApiRuntime/Client/AmpArtaxEndpointTrait.php
src/OpenApiRuntime/Client/Psr7HttplugEndpointTrait.php

This should resolve: https://github.com/janephp/janephp/issues/88
Be aware this is untested, as I do not have a way to confirm at the moment.

Fix issue with incompatible function declaration

---

CHANGELOG.md
src/OpenApi/SchemaParser/SchemaParser.php

Remove warning on OpenApi fresh install with YAML schema

---

src/JsonSchema/Generator/Model/PropertyGenerator.php
src/JsonSchema/Generator/ModelGenerator.php
src/JsonSchema/Guesser/JsonSchema/ObjectGuesser.php
src/JsonSchema/Model/JsonSchema.php
src/JsonSchema/Tests/fixtures/test-default/expected/Model/Test.php
src/JsonSchema/Tests/fixtures/test-default/expected/Model/TestSubObject.php
src/JsonSchema/Tests/fixtures/test-not-strict/expected/Model/Test.php
src/OpenApi/Guesser/OpenApiSchema/SchemaGuesser.php
src/OpenApi/Tests/fixtures/test-nullable/.jane-openapi
src/OpenApi/Tests/fixtures/test-nullable/expected/Client.php
src/OpenApi/Tests/fixtures/test-nullable/expected/Model/Model.php
src/OpenApi/Tests/fixtures/test-nullable/expected/Normalizer/ModelNormalizer.php
src/OpenApi/Tests/fixtures/test-nullable/expected/Normalizer/NormalizerFactory.php
src/OpenApi/Tests/fixtures/test-nullable/schema.json

Fix nullable property for OpenApi

---

documentation/OpenAPI/example.rst
documentation/OpenAPI/introduction.rst
documentation/_static/highlight.css
documentation/index.rst

Add a fully working example for OpenAPI documentation

OpenAPI example

---

src/OpenApi/Generator/HttplugClientGenerator.php

Same as #123 but for `HttplugClientGenerator`

[HttplugClientGenerator] Check if path exists before using it

---

composer.json
src/JsonSchema/Guesser/JsonSchema/ObjectGuesser.php
src/JsonSchema/Model/JsonSchema.php
src/JsonSchema/Normalizer/JsonSchemaNormalizer.php
src/JsonSchema/Tests/LibraryTest.php
src/JsonSchema/Tests/data/json-schema.json
src/JsonSchema/composer.json
src/JsonSchemaRuntime/composer.json
src/OpenApi/composer.json

Upgrade JsonSchema specs step by step from draft-04 to draft-06
First step for #131
Reference https://json-schema.org/draft-06/json-schema-release-notes.html

Upgrade JsonSchema to draft-06

---

src/JsonSchema/Model/JsonSchema.php
src/JsonSchema/Normalizer/JsonSchemaNormalizer.php
src/JsonSchema/Tests/data/json-schema.json

Upgrade JsonSchema specs step by step from draft-06 to draft-07
Second step for #131
Reference https://json-schema.org/draft-07/json-schema-release-notes.html

Upgrade JsonSchema to draft-07

---

src/JsonSchema/Generator/Normalizer/DenormalizerGenerator.php
src/JsonSchema/Model/JsonSchema.php
src/JsonSchema/Normalizer/JsonSchemaNormalizer.php
src/JsonSchema/Tests/data/json-schema.json
src/JsonSchema/Tests/fixtures/additional-properties/expected/Normalizer/AdditionalPropertiesNormalizer.php
src/JsonSchema/Tests/fixtures/additional-properties/expected/Normalizer/PatternPropertiesNormalizer.php
src/JsonSchema/Tests/fixtures/datetime-format/expected/Normalizer/TestNormalizer.php
src/JsonSchema/Tests/fixtures/datetime/expected/Normalizer/TestNormalizer.php
src/JsonSchema/Tests/fixtures/deep-object/expected/Normalizer/TestFooItemNormalizer.php
src/JsonSchema/Tests/fixtures/deep-object/expected/Normalizer/TestNormalizer.php
src/JsonSchema/Tests/fixtures/definitions/expected/Normalizer/BarItemNormalizer.php
src/JsonSchema/Tests/fixtures/definitions/expected/Normalizer/FooNormalizer.php
src/JsonSchema/Tests/fixtures/definitions/expected/Normalizer/HelloWorldNormalizer.php
src/JsonSchema/Tests/fixtures/name-conflict/expected/Normalizer/TestNormalizer.php
src/JsonSchema/Tests/fixtures/one-of/expected/Normalizer/FooNormalizer.php
src/JsonSchema/Tests/fixtures/reserved-words/expected/Normalizer/ListNormalizer.php
src/JsonSchema/Tests/fixtures/test-default/expected/Normalizer/TestNormalizer.php
src/JsonSchema/Tests/fixtures/test-default/expected/Normalizer/TestSubObjectNormalizer.php
src/JsonSchema/Tests/fixtures/test-not-strict/expected/Normalizer/TestNormalizer.php
src/JsonSchema/Tests/fixtures/test-null/expected/Normalizer/TestNormalizer.php

Upgrade JsonSchema specs step by step from draft-07 to 2019-09
Last step for #131
Reference https://json-schema.org/draft/2019-09/release-notes.html
I made some changes to the schema to make it compatible:
- Merged all meta files into same file
- Replaced all `$recursiveRef` by `$ref` property in base schema

Upgrade JsonSchema to 2019-09

---

src/OpenApi/Guesser/OpenApiSchema/OpenApiGuesser.php

Fixes #173

---

src/JsonSchema/Tests/fixtures/array-object-nullable/.jane
src/JsonSchema/Tests/fixtures/array-object-nullable/expected/Model/Attributes.php
src/JsonSchema/Tests/fixtures/array-object-nullable/expected/Model/Document.php
src/JsonSchema/Tests/fixtures/array-object-nullable/expected/Normalizer/AttributesNormalizer.php
src/JsonSchema/Tests/fixtures/array-object-nullable/expected/Normalizer/DocumentNormalizer.php
src/JsonSchema/Tests/fixtures/array-object-nullable/expected/Normalizer/NormalizerFactory.php
src/JsonSchema/Tests/fixtures/array-object-nullable/schema.json

It seems #144 is not a problem anymore since I do have `null` type on getter.

Add test for #144

---

.github/workflows/CI.yml
composer.json
src/AutoMapper/composer.json
src/JsonSchema/Jane.php
src/JsonSchema/composer.json
src/JsonSchemaRuntime/composer.json
src/OpenApi/JaneOpenApi.php
src/OpenApi/composer.json
src/OpenApiRuntime/composer.json

following #181 with some fixes

Symfony 5 compatibility

---

src/JsonSchema/Command/GenerateCommand.php
src/OpenApi/Command/GenerateCommand.php

Adding return values for commands to v4 branch.

Fixed compat with symfony/console >= 5 

---

src/JsonSchemaRuntime/Reference.php

Following #168 and @TerraSkye investigation, this PR introduce local cache for Reference contents and normalize it as json (even if we use YAML).

Local cache for Reference contents

---

composer.json
documentation/JsonSchema/generate.rst
documentation/OpenAPI/generate.rst
src/JsonSchema/Command/GenerateCommand.php
src/JsonSchema/Printer.php
src/JsonSchema/Tests/JaneBaseTest.php
src/JsonSchema/Tests/LibraryTest.php
src/JsonSchema/composer.json
src/OpenApi/Command/GenerateCommand.php
src/OpenApi/Tests/JaneOpenApiResourceTest.php

This branch is on top of #196, please merge it first.
It will introduce removing generated files before generating new ones.
For reviewers, check only this commit https://github.com/janephp/janephp/commit/d59981122608f977d32f74222dcf4c718ea8c9a6 please.

Remove generated code before new generation

---

documentation/AutoMapper/features.rst
documentation/AutoMapper/introduction.rst
documentation/AutoMapper/usage.rst
documentation/index.rst
src/AutoMapper/AbstractAutoMapper.php
src/AutoMapper/AutoMapperInterface.php
src/AutoMapper/AutoMapperRegistryInterface.php
src/AutoMapper/Mapper.php
src/AutoMapper/MapperInterface.php

This PR introduce some documentation for the AutoMapper component and takes some interfaces that were added in the Symfony PR  https://github.com/symfony/symfony/pull/30248 and that can be usefull.

AutoMapper documentation

---

.gitignore
composer.json
src/AutoMapper/Tests/AutoMapperTest.php
src/AutoMapper/composer.json
src/JsonSchema/Tests/Generator/Context/UniqueVariableScopeTest.php
src/JsonSchema/Tests/JaneBaseTest.php
src/JsonSchema/Tests/LibraryTest.php
src/JsonSchema/composer.json
src/JsonSchemaRuntime/Tests/Normalizer/ReferenceNormalizerTest.php
src/JsonSchemaRuntime/Tests/ReferenceTest.php
src/JsonSchemaRuntime/composer.json
src/OpenApi/Tests/JaneOpenApiResourceTest.php
src/OpenApi/composer.json
src/OpenApi2/Tests/JaneOpenApiResourceTest.php
src/OpenApi2/composer.json
src/OpenApiRuntime/Tests/Client/Psr18ClientTest.php
src/OpenApiRuntime/Tests/Client/Psr7EndpointTraitTest.php
src/OpenApiRuntime/Tests/Client/Psr7HttplugClientTest.php
src/OpenApiRuntime/composer.json

This PR upgrade `phpunit` from `v6.x` to `v8.x`

Upgrade phpunit

---

.github/workflows/gitsplit.sh
.github/workflows/gitsplit.yml

Replace actual usage of [jderusse/docker-gitsplit](https://github.com/jderusse/docker-gitsplit) by using [dflydev/git-subsplit](https://github.com/dflydev/git-subsplit) script.

Replace gitsplit

---

documentation/JsonSchema/multi.rst

When dealing with multiple JSON schemas + "global generation" options

Improves JSON multi schemas doc

---

src/JsonSchema/Command/GenerateCommand.php
src/JsonSchema/Generator/Normalizer/NormalizerGenerator.php
src/JsonSchema/Generator/NormalizerGenerator.php
src/JsonSchema/Jane.php
src/OpenApi/JaneOpenApi.php
src/OpenApi/Tests/fixtures/normalizer-force-null-when-nullable/.jane-openapi
src/OpenApi/Tests/fixtures/normalizer-force-null-when-nullable/expected/Client.php
src/OpenApi/Tests/fixtures/normalizer-force-null-when-nullable/expected/Endpoint/TestNullableQueryParameters.php
src/OpenApi/Tests/fixtures/normalizer-force-null-when-nullable/expected/Model/Model.php
src/OpenApi/Tests/fixtures/normalizer-force-null-when-nullable/expected/Normalizer/JaneObjectNormalizer.php
src/OpenApi/Tests/fixtures/normalizer-force-null-when-nullable/expected/Normalizer/ModelNormalizer.php
src/OpenApi/Tests/fixtures/normalizer-force-null-when-nullable/expected/Normalizer/NormalizerFactory.php
src/OpenApi/Tests/fixtures/normalizer-force-null-when-nullable/schema.json
src/OpenApi2/JaneOpenApi.php
src/OpenApiCommon/Command/GenerateCommand.php

:point_up: forcing a null value on non-set property is a wrong idea, we should not do it ~

Else assign null when property has no value is wrong

---

src/OpenApi/Generator/Client/ServerPluginGenerator.php
src/OpenApi/Tests/fixtures/host-with-port-and-base-path/.jane-openapi
src/OpenApi/Tests/fixtures/host-with-port-and-base-path/expected/Client.php
src/OpenApi/Tests/fixtures/host-with-port-and-base-path/expected/Endpoint/TestHost.php
src/OpenApi/Tests/fixtures/host-with-port-and-base-path/expected/Normalizer/JaneObjectNormalizer.php
src/OpenApi/Tests/fixtures/host-with-port-and-base-path/expected/Normalizer/NormalizerFactory.php
src/OpenApi/Tests/fixtures/host-with-port-and-base-path/swagger.json
src/OpenApi/Tests/fixtures/host-with-port/.jane-openapi
src/OpenApi/Tests/fixtures/host-with-port/expected/Client.php
src/OpenApi/Tests/fixtures/host-with-port/expected/Endpoint/TestHost.php
src/OpenApi/Tests/fixtures/host-with-port/expected/Normalizer/JaneObjectNormalizer.php
src/OpenApi/Tests/fixtures/host-with-port/expected/Normalizer/NormalizerFactory.php
src/OpenApi/Tests/fixtures/host-with-port/swagger.json

feat (server port) : handle server port of openapiv3 specification
See @https://github.com/janephp/janephp/issues/281#issue-592661828

Handle server port of openapiv3 specification

---

composer.json
src/JsonSchemaRuntime/Reference.php
src/JsonSchemaRuntime/composer.json

Fixes #294 
Upgrade `league/uri` dependencies to avoid deprecation notices.

Upgrade league/uri

---

CHANGELOG.md
documentation/components/JsonSchema.rst
documentation/components/OpenAPI.rst
documentation/documentation/JsonSchema.rst
documentation/documentation/OpenAPI.rst

Prepare v6.0.0

---

src/JsonSchema/Registry/Schema.php
src/OpenApi2/WhitelistedSchema.php
src/OpenApi3/Tests/fixtures/whitelisted-paths-circular-reference/.jane-openapi
src/OpenApi3/Tests/fixtures/whitelisted-paths-circular-reference/expected/Client.php
src/OpenApi3/Tests/fixtures/whitelisted-paths-circular-reference/expected/Endpoint/GetBaz.php
src/OpenApi3/Tests/fixtures/whitelisted-paths-circular-reference/expected/Endpoint/GetFoo.php
src/OpenApi3/Tests/fixtures/whitelisted-paths-circular-reference/expected/Model/Baz.php
src/OpenApi3/Tests/fixtures/whitelisted-paths-circular-reference/expected/Model/Foo.php
src/OpenApi3/Tests/fixtures/whitelisted-paths-circular-reference/expected/Model/SubBaz.php
src/OpenApi3/Tests/fixtures/whitelisted-paths-circular-reference/expected/Normalizer/BazNormalizer.php
src/OpenApi3/Tests/fixtures/whitelisted-paths-circular-reference/expected/Normalizer/FooNormalizer.php
src/OpenApi3/Tests/fixtures/whitelisted-paths-circular-reference/expected/Normalizer/JaneObjectNormalizer.php
src/OpenApi3/Tests/fixtures/whitelisted-paths-circular-reference/expected/Normalizer/SubBazNormalizer.php
src/OpenApi3/Tests/fixtures/whitelisted-paths-circular-reference/openapi.yaml
src/OpenApi3/WhitelistedSchema.php
src/OpenApiCommon/Registry/Schema.php

Fixes #307 
This PR will block circular relation.

[Whitelist paths] fix infinite loop on circular reference in models

---

src/OpenApi2/Tests/fixtures/exceptions/expected/Client.php
src/OpenApi2/Tests/fixtures/exceptions/expected/Endpoint/TestNoTag.php
src/OpenApi2/Tests/fixtures/exceptions/expected/Exception/TestNoTag600Exception.php
src/OpenApi2/Tests/fixtures/exceptions/swagger.json
src/OpenApi3/JsonSchema/Normalizer/ResponsesNormalizer.php
src/OpenApi3/Tests/fixtures/exceptions/expected/Client.php
src/OpenApi3/Tests/fixtures/exceptions/expected/Endpoint/TestNoTag.php
src/OpenApi3/Tests/fixtures/exceptions/expected/Exception/TestNoTag600Exception.php
src/OpenApi3/Tests/fixtures/exceptions/swagger.json
src/OpenApiCommon/Naming/ExceptionNaming.php

Allow non-standard HTTP codes

---

documentation/documentation/choose.rst

Add some links to help people understand what are JSON Schema & OpenAPI

---

composer.json

Exclude tests from classmap

---

CHANGELOG.md
src/JsonSchema/composer.json
src/OpenApi2/composer.json
src/OpenApiCommon/composer.json
src/OpenApiRuntime/composer.json

Minor v6.1.0 release ~
- Biggest feature will be AutoMapper which is updated from the Symfony PR https://github.com/symfony/symfony/pull/30248 and with some fixes thanks to @odolbeau.
- Also I did a big refactoring onto OpenAPI components in order to mutualise code and avoid duplicates, there is some work to do, but, I think, we are on a good way.

Release v6.1.0
